<a href="https://colab.research.google.com/github/cazlima/exerciciosPython/blob/main/Carinatreinando2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 9
## Exercicio Proposto - Resolucao

In [ ]:
#megasena
import random



In [ ]:
%%timeit
lista=[]

for n in range (10):

  zero=0
  um=0
  dois=0
  tres=0
  quatro=0
  cinco=0
  seis=0

  for i in range (2500000): 

    minha=set(random.sample(range(1,61),6))

    sorteio=set(random.sample(range(1,61),6))

    acertos=minha.intersection(sorteio)

    num_acer=len(acertos)

    if num_acer == 0:
        zero+=1
    elif num_acer == 1:
        um+=1
    elif  num_acer == 2:
        dois+=1
    elif  num_acer == 3:
        tres+=1
    elif  num_acer == 4:
        quatro+=1
    elif  num_acer == 5:
        cinco+=1
        print(i)
        lista.append(i)
        break
    else:
        seis+=1

  print(f'eu acertei um numero {um} vezes')
  print(f'eu acertei dois numeros {dois} vezes')
  print(f'eu acertei tres numeros {tres} vezes')
  print(f'eu acertei quatro numeros {quatro} vezes')
  print(f'eu acertei cinco numeros {cinco} vezes')
  print(f'eu acertei seis numeros {seis} vezes')
summ=sum(lista)
den=len(lista)
media=summ/den
print(media)


221749
eu acertei um numero 84328 vezes
eu acertei dois numeros 21010 vezes
eu acertei tres numeros 2245 vezes
eu acertei quatro numeros 82 vezes
eu acertei cinco numeros 1 vezes
eu acertei seis numeros 0 vezes
214211
eu acertei um numero 81394 vezes
eu acertei dois numeros 20316 vezes
eu acertei tres numeros 2149 vezes
eu acertei quatro numeros 96 vezes
eu acertei cinco numeros 1 vezes
eu acertei seis numeros 0 vezes
22160
eu acertei um numero 8333 vezes
eu acertei dois numeros 2132 vezes
eu acertei tres numeros 218 vezes
eu acertei quatro numeros 8 vezes
eu acertei cinco numeros 1 vezes
eu acertei seis numeros 0 vezes
391147
eu acertei um numero 147597 vezes
eu acertei dois numeros 37346 vezes
eu acertei tres numeros 3946 vezes
eu acertei quatro numeros 198 vezes
eu acertei cinco numeros 1 vezes
eu acertei seis numeros 0 vezes
12011
eu acertei um numero 4570 vezes
eu acertei dois numeros 1099 vezes
eu acertei tres numeros 113 vezes
eu acertei quatro numeros 4 vezes
eu acertei cinco n

In [ ]:
print(round(media))

In [ ]:
%reset

In [ ]:
%whos

In [ ]:


lista=[]

for n in range (1000):

  zero=0
  um=0
  dois=0
  tres=0
  quatro=0
  cinco=0
  seis=0

  for i in range (2500000): 

    minha=set(random.sample(range(1,61),6))

    sorteio=set(random.sample(range(1,61),6))

    acertos=minha.intersection(sorteio)

    num_acer=len(acertos)

    if num_acer == 0:
        zero+=1
    elif num_acer == 1:
        um+=1
    elif  num_acer == 2:
        dois+=1
    elif  num_acer == 3:
        tres+=1
    elif  num_acer == 4:
        quatro+=1
    elif  num_acer == 5:
        cinco+=1
        lista.append(i)
        break
    else:
        seis+=1

summ=sum(lista)
den=len(lista)
media=round(summ/den)
print(f'Para acertar a quina preciso jogar em media {media} vezes')

KeyboardInterrupt: ignored

esse resultado 32075 eh pq eu rodei pra n=1 antes de salvar. quando rodei pra n=1000 deiem torno de 150000vezes que preciso jogar na megasena. nao rodo novamente pq levou uns bons 40 minutos :)

In [ ]:
%reset


# Aula 10

In [ ]:
import random

total=251
preco=4
album=10

completo=[0]*total
#parar=[False]*total
num_pacotes=0


while True:

  pacote=set(random.sample(range(total),4))
  num_pacotes+=1

  for fig in pacote:
    completo[fig]+=1
    
  if all(fig > 0 for fig in completo):
    break

 # parar=[]
 # for fig in completo:
 #   parar.append(fig>0)
 #   if completo[fig]>0:
 #     parar[fig]=True
 
 # if all(parar):
 #   break

print(completo)
print('##')
print(f'Foi preciso comparar {num_pacotes} pacotinhos para completar o album')
gasto=album+(preco*num_pacotes)
print('##')
print(f'O gasto total foi {gasto} reais')


[4, 5, 6, 4, 5, 3, 5, 6, 6, 4, 3, 3, 3, 5, 10, 9, 5, 5, 6, 6, 3, 4, 7, 7, 7, 8, 9, 4, 1, 7, 11, 3, 5, 4, 8, 4, 10, 7, 3, 8, 3, 3, 4, 5, 4, 11, 5, 4, 12, 6, 7, 12, 3, 2, 7, 1, 5, 5, 5, 6, 6, 6, 11, 7, 4, 5, 4, 8, 8, 2, 6, 9, 6, 4, 8, 7, 1, 8, 2, 1, 7, 2, 2, 3, 4, 5, 7, 7, 7, 7, 8, 5, 7, 4, 4, 8, 5, 11, 6, 6, 10, 4, 6, 4, 1, 4, 3, 6, 8, 6, 5, 6, 8, 6, 9, 7, 3, 4, 4, 3, 2, 8, 3, 3, 3, 2, 5, 7, 6, 5, 5, 5, 3, 7, 4, 8, 5, 8, 6, 4, 11, 4, 6, 8, 3, 9, 7, 6, 4, 4, 6, 2, 8, 7, 6, 4, 2, 7, 2, 8, 2, 9, 1, 5, 5, 5, 2, 3, 4, 4, 5, 3, 5, 7, 4, 7, 11, 3, 6, 3, 5, 6, 9, 3, 5, 10, 7, 6, 6, 4, 5, 4, 4, 11, 4, 3, 4, 3, 11, 8, 7, 6, 5, 5, 4, 3, 9, 3, 9, 4, 5, 7, 5, 6, 9, 6, 5, 7, 3, 4, 4, 5, 5, 6, 1, 2, 10, 6, 10, 7, 2, 2, 6, 1, 7, 7, 7, 5, 3, 3, 8, 10, 5, 5, 3, 8, 5, 9, 4, 4, 7]
##
Foi preciso comparar 343 pacotinhos para completar o album
##
O gasto total foi 1382 reais


In [ ]:
trin=[0, 1, 0]
parar=[]
for i in trin:
  parar.append(i>0)
print(parar)

[False, True, False]


In [ ]:
import random

total=251
preco=4
album=10

pcts=[]
precos=[]
test=[]
test2=[]
test3=0
test4=0
test5=0

for n in range (1001):

  num_pacotes=0
  completo=[0]*total
  a=0

  while True:

    pacote=set(random.sample(range(total),4))
    num_pacotes+=1

    for fig in pacote:
      completo[fig]+=1

    if all(fig > 0 for fig in completo):
      break

  gasto=album+(preco*num_pacotes)
  pcts.append(num_pacotes)
  precos.append(gasto)
  

  for i in completo:
    if completo[i]>a:
      a=completo[i]
  test.append(a)
  test2.append(completo.count(1))

pcts_medio=round(sum(pcts)/1000)
preco_medio=round(sum(precos)/1000)
test_medio=round(sum(test)/1000)
test2_medio=round(sum(test2)/1000)

for preco in precos:
  if preco>3000:
    test3 +=1
  elif preco<1500:
    test4 +=1
  elif preco>preco_medio:
    test5 +=1

test3=test3/10
test4=test4/10
test5=test5/10



print(f'Eh preciso comprar {pcts_medio} pacotinhos para completar o album')
print('##')
print(f'O gasto medio para completar eh de {preco_medio} reais')

print(f'A figurinda mais repetida foi repetida em media {test_medio} vezes')
print(f'Em media, {test2_medio} figurinhas nao se repetem ao completar o album')
print(f'A probabilidade de se gastar mais de R$3000 para completar o album eh de {test3}%')
print(f'A probabilidade de se gastar menos de R$1500 para completar o album eh de {test4}%')
print(f'A probabilidade de se gastar mais do que a media para completar o album eh de {test5}%')

Eh preciso comprar 381 pacotinhos para completar o album
##
O gasto medio para completar eh de 1533 reais
A figurinda mais repetida foi repetida em media 11 vezes
Em media, 6 figurinhas nao se repetem ao completar o album
A probabilidade de se gastar mais de R$3000 para completar o album eh de 0.3%
A probabilidade de se gastar menos de R$1500 para completar o album eh de 52.2%
A probabilidade de se gastar mais do que a media para completar o album eh de 43.5%


In [ ]:
# para 1 ou dois amigos

import random

total=251
preco=4
album=10

pcts=[]
precos=[]
test=[]
test2=[]
test3=0
test4=0
test5=0

for n in range (1001):

  num_pacotes=0
  completo=[0]*total
  a=0

  while True:

    pacote=set(random.sample(range(total),4))
    num_pacotes+=1

    for fig in pacote:
      completo[fig]+=1

    if all(fig > 2 for fig in completo):
      break

  gasto=(album+(preco*num_pacotes))/3
  pcts.append(num_pacotes)
  precos.append(gasto)
  

  for i in completo:
    if completo[i]>a:
      a=completo[i]
  test.append(a)
  test2.append(completo.count(1))

pcts_medio=round(sum(pcts)/1000)
preco_medio=round(sum(precos)/1000)
test_medio=round(sum(test)/1000)
test2_medio=round(sum(test2)/1000)

for preco in precos:
  if preco>3000:
    test3 +=1
  elif preco<1500:
    test4 +=1
  elif preco>preco_medio:
    test5 +=1

test3=test3/10
test4=test4/10
test5=test5/10



print(f'Eh preciso comprar {pcts_medio} pacotinhos para completar o album')
print('##')
print(f'O gasto medio para completar eh de {preco_medio} reais')

print(f'A figurinda mais repetida foi repetida em media {test_medio} vezes')
print(f'Em media, {test2_medio} figurinhas nao se repetem ao completar o album')
print(f'A probabilidade de se gastar mais de R$3000 para completar o album eh de {test3}%')
print(f'A probabilidade de se gastar menos de R$1500 para completar o album eh de {test4}%')
print(f'A probabilidade de se gastar mais do que a media para completar o album eh de {test5}%')

Eh preciso comprar 646 pacotinhos para completar o album
##
O gasto medio para completar eh de 864 reais
A figurinda mais repetida foi repetida em media 16 vezes
Em media, 0 figurinhas nao se repetem ao completar o album
A probabilidade de se gastar mais de R$3000 para completar o album eh de 0.0%
A probabilidade de se gastar menos de R$1500 para completar o album eh de 100.1%
A probabilidade de se gastar mais do que a media para completar o album eh de 0.0%


In [ ]:
import random

total=251
preco=4
album=10

pcts=[]
precos=[]

for n in range (1001):

  num_pacotes=0
  completo=[0]*total
  a=0
  contagem=0

  while True:

    pacote=set(random.sample(range(total),4))
    num_pacotes+=1

    for fig in pacote:
      completo[fig]+=1
      if completo[fig]==1:
        contagem+=1

    if contagem>188:
      break

  gasto=album+(preco*num_pacotes)
  pcts.append(num_pacotes)
  precos.append(gasto)
  

  for i in completo:
    if completo[i]>a:
      a=completo[i]
  test.append(a)
  test2.append(completo.count(1))

pcts_medio=round(sum(pcts)/1000)
preco_medio=round(sum(precos)/1000)


print(f'Eh preciso comprar {pcts_medio} pacotinhos para completar 75% do album')
print('##')
print(f'O gasto medio para completar eh de {preco_medio} reais')

Eh preciso comprar 87 pacotinhos para completar 75% do album
##
O gasto medio para completar eh de 359 reais


In [ ]:
a=0
test=[a]
for i in completo:
  if completo[i]>a:
    a=completo[i]
    test.append(a)

print(a)
print(test)


8
[0, 5, 7, 8]


In [ ]:
completo.count(1)

11

In [ ]:
print(precos)

[1442, 1346, 1574, 1070, 2902, 1170, 2310, 1498, 1462, 1346, 1530, 1050, 1466, 1478, 1794, 1414, 1678, 1498, 1322, 1478, 1354, 2750, 1242, 1454, 1650, 1486, 1290, 1878, 1062, 1734, 1562, 1394, 1518, 1422, 1662, 1610, 1294, 1738, 1374, 1138, 1570, 1910, 1958, 1502, 1366, 1902, 1238, 1826, 1438, 1230, 1094, 2250, 1250, 1186, 1226, 1402, 1370, 1410, 1286, 1346, 2170, 1598, 1934, 1850, 1926, 2082, 1346, 1358, 1794, 1634, 1082, 1270, 1814, 1742, 1658, 1610, 1546, 1570, 1198, 1250, 1250, 1714, 1718, 1590, 1622, 1710, 1430, 1166, 1478, 1834, 1298, 1558, 1162, 1406, 1286, 1226, 1266, 1510, 1198, 1466, 1354, 1606, 1366, 1490, 1286, 2634, 1570, 1526, 1666, 1442, 2354, 1290, 1774, 1830, 1778, 1038, 1278, 1906, 2254, 1622, 1498, 1730, 1070, 1290, 1282, 1298, 1442, 1214, 1670, 1170, 1302, 1750, 1570, 1342, 1410, 1950, 1754, 1470, 1506, 1494, 1858, 1534, 1366, 1410, 1482, 950, 1510, 1182, 1338, 1162, 1202, 1618, 1446, 1042, 1574, 1426, 1774, 1210, 1078, 1270, 2218, 1658, 1210, 1370, 1294, 1530, 1450

# Live
## Live notes

In [ ]:
frutas = ['ban', 'mac', 'abc']

for i, fruta in enumerate(frutas):
  print(f'fruta numero {i+1}:',fruta)

fruta numero 1: ban
fruta numero 2: mac
fruta numero 3: abc


# Aula 11 Numpy

In [ ]:
listaa=[1, 2, 3, 4]

import numpy as np
vetor= np.array(listaa)
print(vetor)

matrix= np.array([ [2,4], [5,6] ])
print(matrix)

[1 2 3 4]
[[2 4]
 [5 6]]


In [ ]:
np.array([0]*5)
np.zeros(5)

print([0]*5)
print(np.array([0]*5))
print(np.zeros(5))

print(np.zeros(5,dtype=int))



[0, 0, 0, 0, 0]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [ ]:
c=np.ones(5)
type(c[1])


numpy.float64

In [ ]:
print(np.eye(3))
d=np.array([[1, 2, 3],[1,2,3],[1,2,3] ])
print(d)

e=np.eye(3).dot(d)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
np.eye(3) @ d

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
print(vetor)
matrix1=vetor.reshape(2,2)
print(matrix1)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
g=5.5
print(np.ceil(g))
print(np.floor(g))

6.0
5.0


In [ ]:
h=np.linalg.inv(matrix)
print(h)

[[-0.75   0.5  ]
 [ 0.625 -0.25 ]]


In [ ]:
h @ matrix
# h.dot(matrix)

array([[ 1.00000000e+00, -2.22044605e-16],
       [-5.55111512e-17,  1.00000000e+00]])

In [ ]:
matrix.transpose()

array([[2, 5],
       [4, 6]])

## Exercicio Proposto

In [ ]:
X=np.array([[1, 12], [3,10], [2,11]])
y=np.array([[5], [4], [7]])
m=np.transpose(X)
n=m @ X
o=np.linalg.inv(n)
p=o @ m
b=p @ y

print('A matrix resultante eh:')
print(b)

A matrix resultante eh:
[[-0.01282051]
 [ 0.48717949]]
